<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Service;

class NewServicesSeeder extends Seeder
{
    public function run()
    {
        $services = [
            [
                'id' => 'photography-videography-id',
                'title' => 'Photography & Videography',
                'slug' => 'photography-videography',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'PHOTOGRAPHY & VIDEOGRAPHY',
                    'heading' => 'High-End Visual Production that Commands Attention.',
                    'btn_text' => 'Book a Shoot&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "In a visually driven market, mediocre imagery costs you customers. We produce high-impact, cinematic videography and crisp, editorial-quality photography that elevates your brand’s perceived value and captures your audience's imagination.\n\nFrom lifestyle shoots and sleek product photography to dynamic brand films and social-first video content, we handle the entire production pipeline to ensure your visuals are nothing short of iconic.",
                    'sub_heading' => 'Our Visual Capabilities:',
                    'bullets' => "Commercial & Product Photography\nCinematic Brand Films & Promos\nSocial-First Short-Form Video\nEvent & Lifestyle Coverage",
                    'image' => 'images/service/1786820363_3e21a292ef2acb2f4638dacec719d43784164505.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'Why Premium Visuals<br>Are Non-Negotiable',
                    'description' => 'Transform how your audience perceives your business with imagery that conveys trust, luxury, and uncompromised quality.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'Elevated Brand Prestige',
                        'description' => 'High-end visuals instantly increase the perceived value of your products or services.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Scroll-Stopping Impact',
                        'description' => 'Cinematic quality that cuts through the noise and captures user attention instantly.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Versatile Asset Library',
                        'description' => 'Build a comprehensive library of custom assets for your website, ads, and social media.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Higher Conversion Rates',
                        'description' => 'Showcase your offerings in their best light to build trust and drive faster purchasing decisions.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Story-Driven Connection',
                        'description' => 'Use motion and imagery to evoke emotion and tell the compelling story behind your brand.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'End-to-End Production',
                        'description' => 'We handle location scouting, talent sourcing, lighting, shooting, and flawless post-production.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'From Concept to<br>Cinematic Reality.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Creative Brief & Concepting',
                        'description' => 'We align on your visual goals, aesthetic preferences, and target audience.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Pre-Production & Logistics',
                        'description' => 'We source locations, models, props, and build detailed shot lists and storyboards.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'The Shoot',
                        'description' => 'Our professional crew executes the creative vision on set using cinema-grade equipment.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Post-Production',
                        'description' => 'Expert color grading, retouching, sound design, and editing to polish the final deliverables.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Final Delivery',
                        'description' => 'We hand over high-resolution, platform-optimized formats ready for immediate deployment.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Visual Production Packages.',
                    'highlight' => 'Production.',
                    'description' => 'Choose the scale of production that fits your current campaign requirements.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Studio Starter',
                        'description' => 'Perfect for essential product imagery or headshots.',
                        'price' => '3,500',
                        'price_small' => '/shoot',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Half-day shoot (up to 4 hours)\nProfessional Photographer\n15 High-end retouched images\nBasic lighting setup\n1 Location or Studio setting\nCommercial usage rights',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Brand Campaign',
                        'description' => 'Comprehensive visual refresh for seasonal launches.',
                        'price' => '8,500',
                        'price_small' => '/shoot',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Full-day shoot (up to 8 hours)\nPhotographer & Videographer team\n30 High-end retouched images\n1 Cinematic Brand Video (60s)\n3 Short-form social clips (15s)\nCreative direction & storyboarding',
                        'best_for' => '&bull; Fashion Brands &nbsp;&nbsp;&nbsp; &bull; Product Launches',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => 'Monthly Content Retainer',
                        'description' => 'Consistent, fresh visuals delivered every single month.',
                        'price' => '6,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'One dedicated shoot day per month\nPriority booking and fast turnaround\n20 Retouched lifestyle/product images\n4 Custom short-form Reels/TikToks\nOngoing creative strategy meetings\nDedicated production manager',
                        'best_for' => '&bull; Influencers &nbsp;&nbsp;&nbsp; &bull; Active D2C Brands',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Cinematic Commercial',
                        'description' => 'High-end commercial production for TV or major ad campaigns.',
                        'price' => '15,000+',
                        'price_small' => '/project',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Full cinema crew (Director, DP, Lighting)\nComprehensive casting & location scouting\nAdvanced set design and styling\nExtensive post-production & VFX\nOriginal scoring and sound design\nMaster files for all broadcast formats',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],
            [
                'id' => 'website-development-id',
                'title' => 'Website Development',
                'slug' => 'website-development',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'CUSTOM WEBSITE DEVELOPMENT',
                    'heading' => 'Digital Experiences Built for Speed, Scale & Sales.',
                    'btn_text' => 'Start Your Project&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "Your website is your 24/7 salesperson. We build custom-coded, high-performance web platforms that not only look visually stunning but are engineered from the ground up for seamless user experiences and exceptional conversion rates.\n\nFrom high-converting landing pages to complex e-commerce architectures, our development team ensures flawless functionality, blazing-fast load times, and robust SEO foundations.",
                    'sub_heading' => 'Our Development Expertise:',
                    'bullets' => "Custom Web Applications & CMS\nHigh-Performance E-Commerce Solutions\nResponsive UI/UX Design\nTechnical SEO & Performance Optimization",
                    'image' => 'images/work-meridian.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'Why Custom Web<br>Development Wins',
                    'description' => 'A template cannot reflect a premium brand. Own a digital asset that outpaces competitors and turns visitors into revenue.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'Bespoke UI/UX Design',
                        'description' => 'Unique interfaces tailored specifically to your brand identity, free from the constraints of rigid templates.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Blazing Fast Performance',
                        'description' => 'Optimized codebases and modern tech stacks that ensure sub-second load times for maximum retention.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Conversion-Optimized',
                        'description' => 'Strategic user journeys and frictionless checkout flows designed strictly to increase your bottom line.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Mobile-First Architecture',
                        'description' => 'Flawless rendering and intuitive interaction across smartphones, tablets, and desktop displays.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Advanced Security',
                        'description' => 'Enterprise-grade security protocols to protect your business data and build trust with your customers.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Scalable Infrastructure',
                        'description' => 'Built on robust frameworks that easily scale to handle massive traffic spikes as your business grows.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'From Architecture to<br>Global Launch.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Discovery & Wireframing',
                        'description' => 'We map out the user journey, site architecture, and functional requirements.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'UI/UX Design',
                        'description' => 'We create high-fidelity, interactive prototypes of your new digital experience.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Full-Stack Development',
                        'description' => 'Our engineers write clean, scalable code to bring the design to life on front and back ends.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'QA & Stress Testing',
                        'description' => 'Rigorous testing across browsers, devices, and varying network speeds to ensure stability.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Deployment & Handoff',
                        'description' => 'We handle domain configuration, server deployment, and train your team on the CMS.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Development Tiers.',
                    'highlight' => 'Development.',
                    'description' => 'From high-converting landing pages to complex corporate platforms.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Landing Page',
                        'description' => 'Perfect for campaign launches or lead generation.',
                        'price' => '4,000',
                        'price_small' => '/project',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Custom single-page architecture\nHigh-converting copywriting & UI\nMobile-responsive design\nLead capture forms & CRM integration\nBasic On-page SEO setup\nFast turnaround time',
                        'best_for' => '&bull; Startups &nbsp;&nbsp;&nbsp; &bull; Paid Ad Funnels',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Corporate Website',
                        'description' => 'A robust digital presence for established businesses.',
                        'price' => '12,000',
                        'price_small' => '/project',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Up to 10 custom designed pages\nEasy-to-use Content Management System\nDynamic blog/news section\nAdvanced animations & micro-interactions\nComprehensive SEO foundations\nAnalytics & tracking setup',
                        'best_for' => '&bull; Agencies &nbsp;&nbsp;&nbsp; &bull; Real Estate &nbsp;&nbsp;&nbsp; &bull; Clinics',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => 'E-Commerce Platform',
                        'description' => 'Scalable storefronts engineered to maximize sales.',
                        'price' => '18,500',
                        'price_small' => '/project',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Custom Shopify or WooCommerce build\nFrictionless cart & checkout flows\nAdvanced inventory & variant management\nPayment gateway integrations\nAutomated email flows setup\nConversion rate optimization features',
                        'best_for' => '&bull; Retail Brands &nbsp;&nbsp;&nbsp; &bull; Luxury Goods',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Enterprise Web App',
                        'description' => 'Complex, bespoke web applications with unique logic.',
                        'price' => 'Custom',
                        'price_small' => 'Pricing',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Custom Laravel/React architecture\nThird-party API integrations\nUser dashboards & complex databases\nEnterprise-grade security\nScalable AWS/Cloud infrastructure\nOngoing dedicated maintenance',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],
            [
                'id' => 'fashion-marketing-id',
                'title' => 'Fashion Marketing',
                'slug' => 'fashion-marketing',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'FASHION MARKETING & BRANDING',
                    'heading' => 'Elevate Your Fashion Label to Iconic Status.',
                    'btn_text' => 'Grow Your Brand&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "Fashion is driven by desire, exclusivity, and impeccable aesthetics. We craft bespoke marketing strategies tailored specifically for fashion, apparel, and luxury brands to drive both immense brand awareness and high-volume e-commerce sales.\n\nFrom lookbook campaign rollouts and VIP influencer seeding to high-ROAS Meta advertising strategies, we know exactly what it takes to make consumers obsess over your next collection.",
                    'sub_heading' => 'Our Fashion Expertise:',
                    'bullets' => "Lookbook & Campaign Direction\nFashion E-Commerce Scaling (Paid Ads)\nVIP Influencer & Creator Seeding\nBrand Positioning & Visual Identity",
                    'image' => 'images/work-nova.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'Why Fashion Needs<br>Specialized Marketing',
                    'description' => 'Generic marketing fails in fashion. You need strategies built on trends, aesthetics, and aspirational buying psychology.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'Aspirational Positioning',
                        'description' => 'Elevate your brand narrative to create intense desirability and justify premium price points.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'E-Commerce Scaling',
                        'description' => 'Turn lookbooks into direct sales through highly profitable, ROAS-focused paid ad funnels.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Cult Community Building',
                        'description' => 'Transform casual buyers into loyal brand advocates who anxiously await every new drop.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Influencer Validation',
                        'description' => 'Strategic product seeding to tastemakers that align with your brand’s specific aesthetic.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Omnichannel Campaigns',
                        'description' => 'Cohesive campaign rollouts across TikTok, Instagram, Email, and your online storefront.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Trend Capitalization',
                        'description' => 'Stay ahead of the curve by leveraging real-time cultural moments and audio trends.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'From Concept to<br>Sold-Out Drops.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Brand & Aesthetic Audit',
                        'description' => 'We analyze your current positioning, visual language, and competitor landscape.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Campaign & Drop Strategy',
                        'description' => 'We architect the entire promotional rollout for your upcoming collections or core items.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Creative & Asset Production',
                        'description' => 'We execute lookbook shoots and produce scroll-stopping video ads tailored for social.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Ad Funnel Execution',
                        'description' => 'We launch targeted Meta and TikTok ad campaigns designed for immediate e-commerce conversions.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Analysis & Scaling',
                        'description' => 'We ruthlessly scale the winning ads and optimize the funnel to maximize your profit margins.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Fashion Growth Tiers.',
                    'highlight' => 'Growth.',
                    'description' => 'Comprehensive packages built for emerging and established fashion houses.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Emerging Label',
                        'description' => 'Perfect for new brands looking to make their mark.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Instagram & TikTok Management\n12 Fashion-forward posts/month\n4 Vertical Video Reels\nBasic Influencer Seeding (3/mo)\nMonthly Content Planning\nCommunity Management',
                        'best_for' => '&bull; New Streetwear Brands &nbsp;&nbsp;&nbsp; &bull; Accessories',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Collection Scale',
                        'description' => 'Designed for brands actively pushing e-commerce volume.',
                        'price' => '8,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in Emerging Label\nMeta & TikTok Paid Ad Management\n1 Professional Lookbook Shoot/month\nVIP Influencer Seeding (10/mo)\nEmail Marketing Newsletter (2/mo)\nAdvanced E-Commerce Reporting',
                        'best_for' => '&bull; Active D2C Fashion &nbsp;&nbsp;&nbsp; &bull; Boutique Labels',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Iconic Brand',
                        'description' => 'For fashion houses aiming for category dominance.',
                        'price' => '14,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Omnichannel Ad Scaling\nHigh-end Editorial Campaign Production\nDaily Stories & Rapid Trend Response\nExtensive Global Influencer Outreach\nPR & Digital Publication Placements\nFull Funnel Conversion Optimization',
                        'best_for' => '&bull; Luxury Fashion &nbsp;&nbsp;&nbsp; &bull; Established Retailers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Your entire fashion marketing department, outsourced.',
                        'price' => '20,000+',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Complete Brand & Creative Direction\nAll Social & Paid Ad Management\nWebsite UI/UX Optimization\nFull-scale Video & Photo Production\nDedicated Fashion Marketing Team\nExclusive Brand Partnerships',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ]
        ];

        foreach ($services as $s) {
            Service::updateOrCreate(['slug' => $s['slug']], $s);
        }
    }
}
