<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Service;

class ServiceSeeder extends Seeder
{
    public function run()
    {
        Service::truncate();

        $services = [
  0 => [
    'id' => '1',
    'title' => 'Events Marketing',
    'show_in_footer' => false,
    'slug' => 'events-marketing',
    'hero' => [
      'small_text' => 'EVENTS MARKETING',
      'heading' => 'Pack the Room. Build the Hype.',
      'btn_text' => 'Book a Discovery Call&nbsp; →',
      'btn_link' => '/book-now',
      'image' => 'assets/pdf/asset-12.png',
    ],
    'overview' => [
      'label' => 'OVERVIEW',
      'description' => 'Whether you\'re launching a new venue, hosting an exclusive brand activation, or organizing a massive festival, our Events Marketing strategies ensure your event is the talk of the town.

We combine hyper-local digital advertising, strategic influencer partnerships, and compelling visual storytelling to drive ticket sales, boost RSVP rates, and create FOMO that guarantees a packed house.',
      'sub_heading' => 'Our Event Marketing Arsenal:',
      'bullets' => 'Pre-Event Hype Campaigns
Influencer & VIP Guest Outreach
Hyper-Local Paid Advertising
Real-Time Event Coverage',
      'image' => 'assets/pdf/asset-08.png',
    ],
    'benefits_header' => NULL,
    'benefits' => [
      0 => [
        'title' => 'Maximized Attendance',
        'description' => 'Targeted advertising and influencer hype designed specifically to drive high-volume ticket sales and RSVPs.',
        'icon' => 'assets/icons/benefit-brand.png',
    ],
      1 => [
        'title' => 'Viral Pre-Event Buzz',
        'description' => 'We create unmissable social media campaigns that build anticipation and establish your event as a must-attend experience.',
        'icon' => 'assets/icons/benefit-engagement.png',
    ],
      2 => [
        'title' => 'Live Coverage',
        'description' => 'Real-time social media management and content capture during the event to amplify reach to those who couldn\'t make it.',
        'icon' => 'assets/icons/benefit-audience.png',
    ],
      3 => [
        'title' => 'Sponsor ROI',
        'description' => 'Showcase sponsor activations effectively, ensuring high visibility and return on investment for your partners.',
        'icon' => 'assets/icons/benefit-authority.png',
    ],
      4 => [
        'title' => 'Post-Event Momentum',
        'description' => 'Capitalize on event success with wrap-up videos, galleries, and remarketing campaigns for your next edition.',
        'icon' => 'assets/icons/benefit-time.png',
    ],
      5 => [
        'title' => 'Hyper-Local Targeting',
        'description' => 'Pinpoint advertising that reaches the exact demographic in your city who are most likely to attend.',
        'icon' => 'assets/icons/benefit-growth.png',
    ],
    ],
    'process_header' => NULL,
    'process' => [
      0 => [
        'title' => 'Strategy & Hook',
        'description' => 'Defining the event\'s unique selling proposition and building the core marketing message.',
        'icon' => 'images/service/1786821688_search.svg',
    ],
      1 => [
        'title' => 'Teaser Campaigns',
        'description' => 'Launching mysterious and exciting pre-event digital campaigns to capture early interest.',
        'icon' => 'images/service/1786821709_Strategize.svg',
    ],
      2 => [
        'title' => 'Aggressive Push',
        'description' => 'Deploying targeted ads and influencer collaborations to drive ticket sales and RSVPs.',
        'icon' => 'images/service/1786821721_create.svg',
    ],
      3 => [
        'title' => 'Live Amplification',
        'description' => 'On-the-ground social media coverage capturing the atmosphere and key moments as they happen.',
        'icon' => 'images/service/1786821738_publish.svg',
    ],
      4 => [
        'title' => 'Post-Event Wrap',
        'description' => 'Publishing high-quality recap content and analyzing campaign performance metrics.',
        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
    ],
    ],
    'pricing_header' => [
      'heading' => 'From Presence to Market Dominance.',
      'highlight' => 'Market Dominance.',
      'description' => 'Choose the level of strategy, creativity, and support your brand needs to grow, scale, and lead.',
    ],
    'pricing' => [
      0 => [
        'id' => '1',
        'name' => 'Black',
        'description' => 'Perfect for startups and growing brands.',
        'price' => '4,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social media strategy\\n2 social media platforms\\n12 premium posts/month\\n4 high-quality Reels\\nCaption writing & hashtag research\\nContent scheduling\\nMonthly analytics report\\nDedicated Account Manager',
        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
        'badge_text' => NULL,
    ],
      1 => [
        'id' => '2',
        'name' => 'Signature',
        'description' => 'Designed for brands ready to scale.',
        'price' => '7,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in BLACK\\nUp to 3 platforms\\n20 premium posts/month\\n8 Reels\\nCommunity Management\\nMonthly content planning\\nOne professional content shoot/month\\nCompetitor analysis\\nMonthly strategy meeting',
        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
        'badge_text' => NULL,
    ],
      2 => [
        'id' => '3',
        'name' => '✨ Icon',
        'description' => 'For brands that want to dominate their industry.',
        'price' => '12,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in SIGNATURE\\nUp to 4 platforms\\n30 premium posts/month\\n12 cinematic Reels\\nDaily Stories\\nFull Community Management\\nProfessional photography & videography\\nInfluencer outreach\\nAdvanced analytics & KPI reporting\\nPriority support',
        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
        'badge_text' => NULL,
    ],
      3 => [
        'id' => '4',
        'name' => 'Black Line 360°',
        'description' => 'Everything your brand needs under one agency.',
        'price' => '18,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social Media Management\\nContent Creation\\nWebsite Management\\nSEO\\nGoogle Ads\\nMeta Ads\\nTikTok Ads\\nEmail Marketing\\nInfluencer Marketing\\nMonthly Strategy Sessions\\nPerformance Reports\\nDedicated Marketing Team',
        'best_for' => NULL,
        'badge_text' => NULL,
    ],
    ],
    'created_at' => '2026-08-19T12:56:34.000000Z',
    'updated_at' => '2026-08-19T13:04:46.000000Z',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    ],
  1 => [
    'id' => 'fashion-marketing-id',
    'title' => 'Fashion Marketing',
    'show_in_footer' => false,
    'slug' => 'fashion-marketing',
    'hero' => [
      'small_text' => 'FASHION MARKETING & BRANDING',
      'heading' => 'Elevate Your Fashion Label to Iconic Status.',
      'btn_text' => 'Grow Your Brand&nbsp; →',
      'btn_link' => '/book-now',
      'image' => 'images/service/1786819879_service-page-banner.jpg',
    ],
    'overview' => [
      'label' => 'OVERVIEW',
      'description' => 'Fashion is driven by desire, exclusivity, and impeccable aesthetics. We craft bespoke marketing strategies tailored specifically for fashion, apparel, and luxury brands to drive both immense brand awareness and high-volume e-commerce sales.

From lookbook campaign rollouts and VIP influencer seeding to high-ROAS Meta advertising strategies, we know exactly what it takes to make consumers obsess over your next collection.',
      'sub_heading' => 'Our Fashion Expertise:',
      'bullets' => 'Lookbook & Campaign Direction
Fashion E-Commerce Scaling (Paid Ads)
VIP Influencer & Creator Seeding
Brand Positioning & Visual Identity',
      'image' => 'images/work-nova.jpg',
    ],
    'benefits_header' => [
      'heading' => 'Why Fashion Needs<br>Specialized Marketing',
      'description' => 'Generic marketing fails in fashion. You need strategies built on trends, aesthetics, and aspirational buying psychology.',
    ],
    'benefits' => [
      0 => [
        'id' => '1',
        'icon' => 'assets/icons/benefit-brand.png',
        'title' => 'Aspirational Positioning',
        'description' => 'Elevate your brand narrative to create intense desirability and justify premium price points.',
    ],
      1 => [
        'id' => '2',
        'icon' => 'assets/icons/benefit-growth.png',
        'title' => 'E-Commerce Scaling',
        'description' => 'Turn lookbooks into direct sales through highly profitable, ROAS-focused paid ad funnels.',
    ],
      2 => [
        'id' => '3',
        'icon' => 'assets/icons/benefit-audience.png',
        'title' => 'Cult Community Building',
        'description' => 'Transform casual buyers into loyal brand advocates who anxiously await every new drop.',
    ],
      3 => [
        'id' => '4',
        'icon' => 'assets/icons/benefit-authority.png',
        'title' => 'Influencer Validation',
        'description' => 'Strategic product seeding to tastemakers that align with your brand’s specific aesthetic.',
    ],
      4 => [
        'id' => '5',
        'icon' => 'assets/icons/benefit-engagement.png',
        'title' => 'Omnichannel Campaigns',
        'description' => 'Cohesive campaign rollouts across TikTok, Instagram, Email, and your online storefront.',
    ],
      5 => [
        'id' => '6',
        'icon' => 'assets/icons/benefit-time.png',
        'title' => 'Trend Capitalization',
        'description' => 'Stay ahead of the curve by leveraging real-time cultural moments and audio trends.',
    ],
    ],
    'process_header' => [
      'subheading' => 'PROCESS',
      'heading' => 'From Concept to<br>Sold-Out Drops.',
    ],
    'process' => [
      0 => [
        'id' => '1',
        'title' => 'Brand & Aesthetic Audit',
        'description' => 'We analyze your current positioning, visual language, and competitor landscape.',
        'icon' => 'images/service/1786821688_search.svg',
    ],
      1 => [
        'id' => '2',
        'title' => 'Campaign & Drop Strategy',
        'description' => 'We architect the entire promotional rollout for your upcoming collections or core items.',
        'icon' => 'images/service/1786821709_Strategize.svg',
    ],
      2 => [
        'id' => '3',
        'title' => 'Creative & Asset Production',
        'description' => 'We execute lookbook shoots and produce scroll-stopping video ads tailored for social.',
        'icon' => 'images/service/1786821721_create.svg',
    ],
      3 => [
        'id' => '4',
        'title' => 'Ad Funnel Execution',
        'description' => 'We launch targeted Meta and TikTok ad campaigns designed for immediate e-commerce conversions.',
        'icon' => 'images/service/1786821738_publish.svg',
    ],
      4 => [
        'id' => '5',
        'title' => 'Analysis & Scaling',
        'description' => 'We ruthlessly scale the winning ads and optimize the funnel to maximize your profit margins.',
        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
    ],
    ],
    'pricing_header' => [
      'heading' => 'From Presence to Market Dominance.',
      'highlight' => 'Market Dominance.',
      'description' => 'Choose the level of strategy, creativity, and support your brand needs to grow, scale, and lead.',
    ],
    'pricing' => [
      0 => [
        'id' => '1',
        'name' => 'Black',
        'description' => 'Perfect for startups and growing brands.',
        'price' => '4,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social media strategy\\n2 social media platforms\\n12 premium posts/month\\n4 high-quality Reels\\nCaption writing & hashtag research\\nContent scheduling\\nMonthly analytics report\\nDedicated Account Manager',
        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
        'badge_text' => NULL,
    ],
      1 => [
        'id' => '2',
        'name' => 'Signature',
        'description' => 'Designed for brands ready to scale.',
        'price' => '7,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in BLACK\\nUp to 3 platforms\\n20 premium posts/month\\n8 Reels\\nCommunity Management\\nMonthly content planning\\nOne professional content shoot/month\\nCompetitor analysis\\nMonthly strategy meeting',
        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
        'badge_text' => NULL,
    ],
      2 => [
        'id' => '3',
        'name' => '✨ Icon',
        'description' => 'For brands that want to dominate their industry.',
        'price' => '12,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in SIGNATURE\\nUp to 4 platforms\\n30 premium posts/month\\n12 cinematic Reels\\nDaily Stories\\nFull Community Management\\nProfessional photography & videography\\nInfluencer outreach\\nAdvanced analytics & KPI reporting\\nPriority support',
        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
        'badge_text' => NULL,
    ],
      3 => [
        'id' => '4',
        'name' => 'Black Line 360°',
        'description' => 'Everything your brand needs under one agency.',
        'price' => '18,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social Media Management\\nContent Creation\\nWebsite Management\\nSEO\\nGoogle Ads\\nMeta Ads\\nTikTok Ads\\nEmail Marketing\\nInfluencer Marketing\\nMonthly Strategy Sessions\\nPerformance Reports\\nDedicated Marketing Team',
        'best_for' => NULL,
        'badge_text' => NULL,
    ],
    ],
    'created_at' => '2026-08-19T12:51:06.000000Z',
    'updated_at' => '2026-08-19T12:51:06.000000Z',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    ],
  2 => [
    'id' => 'influencer-marketing-id',
    'title' => 'Influencer Marketing',
    'show_in_footer' => false,
    'slug' => 'influencer-marketing',
    'hero' => [
      'small_text' => 'INFLUENCER MARKETING & TALENT PARTNERSHIPS',
      'heading' => 'Harness the Power of Authentic, High-Converting Creator Endorsement.',
      'btn_text' => 'Launch Creator Campaigns&nbsp; →',
      'btn_link' => '/book-now',
      'image' => 'images/service/1786819879_service-page-banner.jpg',
    ],
    'overview' => [
      'label' => 'OVERVIEW',
      'description' => 'Consumer trust is built through authentic third-party validation. We connect your brand with carefully curated creators, tastemakers, and niche authority figures whose audiences align seamlessly with your ideal customer profile.

From talent identification and contract negotiations to creative briefs, gifting campaigns, and ROI tracking, we manage seamless influencer activations that drive genuine engagement and sales.',
      'sub_heading' => 'Our Influencer Management:',
      'bullets' => 'Creator Discovery & Audience Vetting
Contract Negotiations & Usage Rights
Creative Briefing & Campaign Coordination
Affiliate Tracking, Whitelisting & ROI Analysis',
      'image' => 'images/work-osteria.jpg',
    ],
    'benefits_header' => [
      'heading' => 'Why Influencer<br>Endorsement Outperforms<br>Standard Ads',
      'description' => 'Leverage established trust, cultural credibility, and authentic community connections to scale brand growth.',
    ],
    'benefits' => [
      0 => [
        'id' => '1',
        'icon' => 'assets/icons/benefit-authority.png',
        'title' => 'High-Trust Endorsements',
        'description' => 'Audiences purchase faster when products are recommended by creators they know and trust.',
    ],
      1 => [
        'id' => '2',
        'icon' => 'assets/icons/benefit-audience.png',
        'title' => 'Zero Fake Followers',
        'description' => 'Rigorous vetting to ensure real engagement rates, clean demographic data, and active followers.',
    ],
      2 => [
        'id' => '3',
        'icon' => 'assets/icons/benefit-brand.png',
        'title' => 'High-Volume UGC Library',
        'description' => 'Accumulate a library of user-generated content for use across paid ads and organic channels.',
    ],
      3 => [
        'id' => '4',
        'icon' => 'assets/icons/benefit-growth.png',
        'title' => 'Creator Whitelisting',
        'description' => 'Run paid ads directly through creators\' personal accounts for lower CPA and higher click-through.',
    ],
      4 => [
        'id' => '5',
        'icon' => 'assets/icons/benefit-time.png',
        'title' => 'Turnkey Management',
        'description' => 'We handle all logistics, product gifting deliveries, contracts, compliance, and payments.',
    ],
      5 => [
        'id' => '6',
        'icon' => 'assets/icons/benefit-engagement.png',
        'title' => 'Trackable Revenue & ROI',
        'description' => 'Transparent tracking via customized promo codes, affiliate links, and pixel conversion data.',
    ],
    ],
    'process_header' => [
      'subheading' => 'PROCESS',
      'heading' => 'From<br>Talent Sourcing to<br>Scalable<br>Conversions.',
    ],
    'process' => [
      0 => [
        'id' => '1',
        'title' => 'Creator Alignment',
        'description' => 'We identify and vet creators whose audience demographics match your exact buyer persona.',
        'icon' => 'images/service/1786821688_search.svg',
    ],
      1 => [
        'id' => '2',
        'title' => 'Negotiation & Legal',
        'description' => 'We handle talent outreach, contract terms, digital usage rights, deliverables, and timelines.',
        'icon' => 'images/service/1786821709_Strategize.svg',
    ],
      2 => [
        'id' => '3',
        'title' => 'Creative Briefing',
        'description' => 'We supply creative briefs that empower authentic expression while safeguarding brand messaging.',
        'icon' => 'images/service/1786821721_create.svg',
    ],
      3 => [
        'id' => '4',
        'title' => 'Campaign Rollout',
        'description' => 'We manage product delivery, review pre-publish drafts, and coordinate synchronized posting dates.',
        'icon' => 'images/service/1786821738_publish.svg',
    ],
      4 => [
        'id' => '5',
        'title' => 'Whitelisting & ROI',
        'description' => 'We amplify top creator posts with paid ads and provide comprehensive revenue analytics.',
        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
    ],
    ],
    'pricing_header' => [
      'heading' => 'Scalable Influencer Programs.',
      'highlight' => 'Influencer Programs.',
      'description' => 'Targeted campaigns designed to build credibility and drive measurable consumer demand.',
    ],
    'pricing' => [
      0 => [
        'id' => '1',
        'name' => 'Black',
        'description' => 'Perfect for startups and growing brands.',
        'price' => '4,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social media strategy\\n2 social media platforms\\n12 premium posts/month\\n4 high-quality Reels\\nCaption writing & hashtag research\\nContent scheduling\\nMonthly analytics report\\nDedicated Account Manager',
        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
        'badge_text' => NULL,
    ],
      1 => [
        'id' => '2',
        'name' => 'Signature',
        'description' => 'Designed for brands ready to scale.',
        'price' => '7,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in BLACK\\nUp to 3 platforms\\n20 premium posts/month\\n8 Reels\\nCommunity Management\\nMonthly content planning\\nOne professional content shoot/month\\nCompetitor analysis\\nMonthly strategy meeting',
        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
        'badge_text' => NULL,
    ],
      2 => [
        'id' => '3',
        'name' => '✨ Icon',
        'description' => 'For brands that want to dominate their industry.',
        'price' => '12,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in SIGNATURE\\nUp to 4 platforms\\n30 premium posts/month\\n12 cinematic Reels\\nDaily Stories\\nFull Community Management\\nProfessional photography & videography\\nInfluencer outreach\\nAdvanced analytics & KPI reporting\\nPriority support',
        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
        'badge_text' => NULL,
    ],
      3 => [
        'id' => '4',
        'name' => 'Black Line 360°',
        'description' => 'Everything your brand needs under one agency.',
        'price' => '18,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social Media Management\\nContent Creation\\nWebsite Management\\nSEO\\nGoogle Ads\\nMeta Ads\\nTikTok Ads\\nEmail Marketing\\nInfluencer Marketing\\nMonthly Strategy Sessions\\nPerformance Reports\\nDedicated Marketing Team',
        'best_for' => NULL,
        'badge_text' => NULL,
    ],
    ],
    'created_at' => '2026-08-19T12:51:06.000000Z',
    'updated_at' => '2026-08-19T12:51:06.000000Z',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    ],
  3 => [
    'id' => 'paid-advertising-id',
    'title' => 'Paid Advertising',
    'show_in_footer' => false,
    'slug' => 'paid-advertising',
    'hero' => [
      'small_text' => 'PAID ADVERTISING & PERFORMANCE MARKETING',
      'heading' => 'Turn Ad Spend into Predictable, Profitable Revenue.',
      'btn_text' => 'Scale Your Revenue&nbsp; →',
      'btn_link' => '/book-now',
      'image' => 'images/service/1786819879_service-page-banner.jpg',
    ],
    'overview' => [
      'label' => 'OVERVIEW',
      'description' => 'Stop burning budget on unoptimized ads. We engineer high-performing ad campaigns across Meta, Google, TikTok, and LinkedIn designed for maximum ROI and predictable scaling.

From conversion-focused ad creatives and precise audience targeting to continuous A/B testing and funnel optimization, we transform digital advertising into your most reliable customer acquisition engine.',
      'sub_heading' => 'Our Advertising Capabilities:',
      'bullets' => 'Meta Ads (Instagram & Facebook)
Google Search, Display & Performance Max
TikTok & LinkedIn Paid Campaigns
Conversion Rate & Retargeting Funnels',
      'image' => 'images/work-meridian.jpg',
    ],
    'benefits_header' => [
      'heading' => 'Why Performance<br>Advertising Drives<br>Measurable Scale',
      'description' => 'Eliminate guesswork with scientific performance marketing, lower customer acquisition costs, and higher return on ad spend (ROAS).',
    ],
    'benefits' => [
      0 => [
        'id' => '1',
        'icon' => 'assets/icons/benefit-growth.png',
        'title' => 'Predictable ROAS',
        'description' => 'Scalable advertising frameworks designed to reliably deliver 3x-8x return on your advertising budget.',
    ],
      1 => [
        'id' => '2',
        'icon' => 'assets/icons/benefit-audience.png',
        'title' => 'Precision Targeting',
        'description' => 'Reach high-intent buyers based on real demographic, behavioral, and interest intelligence.',
    ],
      2 => [
        'id' => '3',
        'icon' => 'assets/icons/benefit-brand.png',
        'title' => 'High-Converting Creatives',
        'description' => 'Dynamic video hooks, static graphics, and persuasive copywriting built to convert scrollers into buyers.',
    ],
      3 => [
        'id' => '4',
        'icon' => 'assets/icons/benefit-engagement.png',
        'title' => 'Full-Funnel Retargeting',
        'description' => 'Re-engage warm prospects who visited your site or engaged with your brand until they convert.',
    ],
      4 => [
        'id' => '5',
        'icon' => 'assets/icons/benefit-authority.png',
        'title' => 'Transparent Attribution',
        'description' => 'Clear attribution models, live KPI dashboards, and deep metric insights with zero vanity metrics.',
    ],
      5 => [
        'id' => '6',
        'icon' => 'assets/icons/benefit-time.png',
        'title' => 'Rapid Budget Scaling',
        'description' => 'Seamlessly increase ad spend while maintaining profitable cost-per-acquisition (CPA) and margin.',
    ],
    ],
    'process_header' => [
      'subheading' => 'PROCESS',
      'heading' => 'From<br>Data Audit to<br>Exponential<br>Return.',
    ],
    'process' => [
      0 => [
        'id' => '1',
        'title' => 'Audit & Tracking',
        'description' => 'We audit existing ad accounts, install server-side pixel tracking, and verify conversion APIs.',
        'icon' => 'images/service/1786821688_search.svg',
    ],
      1 => [
        'id' => '2',
        'title' => 'Funnel Architecture',
        'description' => 'We design full-funnel ad architectures tailored to cold, warm, and hot buyer segments.',
        'icon' => 'images/service/1786821709_Strategize.svg',
    ],
      2 => [
        'id' => '3',
        'title' => 'Creative Production',
        'description' => 'We produce thumb-stopping ad creatives, direct-response hooks, and persuasive copy.',
        'icon' => 'images/service/1786821721_create.svg',
    ],
      3 => [
        'id' => '4',
        'title' => 'Testing & Launch',
        'description' => 'We deploy multivariate testing across audiences, placements, offers, and creative variations.',
        'icon' => 'images/service/1786821738_publish.svg',
    ],
      4 => [
        'id' => '5',
        'title' => 'Scale & Optimize',
        'description' => 'We allocate budget aggressively to winning ads and continuously lower acquisition costs.',
        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
    ],
    ],
    'pricing_header' => [
      'heading' => 'Transparent Ad Management for High Growth.',
      'highlight' => 'High Growth.',
      'description' => 'Select the performance management tier that aligns with your ad spend and revenue goals.',
    ],
    'pricing' => [
      0 => [
        'id' => '1',
        'name' => 'Black',
        'description' => 'Perfect for startups and growing brands.',
        'price' => '4,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social media strategy\\n2 social media platforms\\n12 premium posts/month\\n4 high-quality Reels\\nCaption writing & hashtag research\\nContent scheduling\\nMonthly analytics report\\nDedicated Account Manager',
        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
        'badge_text' => NULL,
    ],
      1 => [
        'id' => '2',
        'name' => 'Signature',
        'description' => 'Designed for brands ready to scale.',
        'price' => '7,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in BLACK\\nUp to 3 platforms\\n20 premium posts/month\\n8 Reels\\nCommunity Management\\nMonthly content planning\\nOne professional content shoot/month\\nCompetitor analysis\\nMonthly strategy meeting',
        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
        'badge_text' => NULL,
    ],
      2 => [
        'id' => '3',
        'name' => '✨ Icon',
        'description' => 'For brands that want to dominate their industry.',
        'price' => '12,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in SIGNATURE\\nUp to 4 platforms\\n30 premium posts/month\\n12 cinematic Reels\\nDaily Stories\\nFull Community Management\\nProfessional photography & videography\\nInfluencer outreach\\nAdvanced analytics & KPI reporting\\nPriority support',
        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
        'badge_text' => NULL,
    ],
      3 => [
        'id' => '4',
        'name' => 'Black Line 360°',
        'description' => 'Everything your brand needs under one agency.',
        'price' => '18,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social Media Management\\nContent Creation\\nWebsite Management\\nSEO\\nGoogle Ads\\nMeta Ads\\nTikTok Ads\\nEmail Marketing\\nInfluencer Marketing\\nMonthly Strategy Sessions\\nPerformance Reports\\nDedicated Marketing Team',
        'best_for' => NULL,
        'badge_text' => NULL,
    ],
    ],
    'created_at' => '2026-08-19T12:51:06.000000Z',
    'updated_at' => '2026-08-19T12:51:06.000000Z',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    ],
  4 => [
    'id' => 'photography-videography-id',
    'title' => 'Photography & Videography',
    'show_in_footer' => false,
    'slug' => 'photography-videography',
    'hero' => [
      'small_text' => 'PHOTOGRAPHY & VIDEOGRAPHY',
      'heading' => 'High-End Visual Production that Commands Attention.',
      'btn_text' => 'Book a Shoot&nbsp; →',
      'btn_link' => '/book-now',
      'image' => 'images/service/1786819879_service-page-banner.jpg',
    ],
    'overview' => [
      'label' => 'OVERVIEW',
      'description' => 'In a visually driven market, mediocre imagery costs you customers. We produce high-impact, cinematic videography and crisp, editorial-quality photography that elevates your brand’s perceived value and captures your audience\'s imagination.

From lifestyle shoots and sleek product photography to dynamic brand films and social-first video content, we handle the entire production pipeline to ensure your visuals are nothing short of iconic.',
      'sub_heading' => 'Our Visual Capabilities:',
      'bullets' => 'Commercial & Product Photography
Cinematic Brand Films & Promos
Social-First Short-Form Video
Event & Lifestyle Coverage',
      'image' => 'images/service/1786820363_3e21a292ef2acb2f4638dacec719d43784164505.jpg',
    ],
    'benefits_header' => [
      'heading' => 'Why Premium Visuals<br>Are Non-Negotiable',
      'description' => 'Transform how your audience perceives your business with imagery that conveys trust, luxury, and uncompromised quality.',
    ],
    'benefits' => [
      0 => [
        'id' => '1',
        'icon' => 'assets/icons/benefit-brand.png',
        'title' => 'Elevated Brand Prestige',
        'description' => 'High-end visuals instantly increase the perceived value of your products or services.',
    ],
      1 => [
        'id' => '2',
        'icon' => 'assets/icons/benefit-engagement.png',
        'title' => 'Scroll-Stopping Impact',
        'description' => 'Cinematic quality that cuts through the noise and captures user attention instantly.',
    ],
      2 => [
        'id' => '3',
        'icon' => 'assets/icons/benefit-audience.png',
        'title' => 'Versatile Asset Library',
        'description' => 'Build a comprehensive library of custom assets for your website, ads, and social media.',
    ],
      3 => [
        'id' => '4',
        'icon' => 'assets/icons/benefit-growth.png',
        'title' => 'Higher Conversion Rates',
        'description' => 'Showcase your offerings in their best light to build trust and drive faster purchasing decisions.',
    ],
      4 => [
        'id' => '5',
        'icon' => 'assets/icons/benefit-authority.png',
        'title' => 'Story-Driven Connection',
        'description' => 'Use motion and imagery to evoke emotion and tell the compelling story behind your brand.',
    ],
      5 => [
        'id' => '6',
        'icon' => 'assets/icons/benefit-time.png',
        'title' => 'End-to-End Production',
        'description' => 'We handle location scouting, talent sourcing, lighting, shooting, and flawless post-production.',
    ],
    ],
    'process_header' => [
      'subheading' => 'PROCESS',
      'heading' => 'From Concept to<br>Cinematic Reality.',
    ],
    'process' => [
      0 => [
        'id' => '1',
        'title' => 'Creative Brief & Concepting',
        'description' => 'We align on your visual goals, aesthetic preferences, and target audience.',
        'icon' => 'images/service/1786821688_search.svg',
    ],
      1 => [
        'id' => '2',
        'title' => 'Pre-Production & Logistics',
        'description' => 'We source locations, models, props, and build detailed shot lists and storyboards.',
        'icon' => 'images/service/1786821709_Strategize.svg',
    ],
      2 => [
        'id' => '3',
        'title' => 'The Shoot',
        'description' => 'Our professional crew executes the creative vision on set using cinema-grade equipment.',
        'icon' => 'images/service/1786821721_create.svg',
    ],
      3 => [
        'id' => '4',
        'title' => 'Post-Production',
        'description' => 'Expert color grading, retouching, sound design, and editing to polish the final deliverables.',
        'icon' => 'images/service/1786821738_publish.svg',
    ],
      4 => [
        'id' => '5',
        'title' => 'Final Delivery',
        'description' => 'We hand over high-resolution, platform-optimized formats ready for immediate deployment.',
        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
    ],
    ],
    'pricing_header' => [
      'heading' => 'From Presence to Market Dominance.',
      'highlight' => 'Market Dominance.',
      'description' => 'Choose the level of strategy, creativity, and support your brand needs to grow, scale, and lead.',
    ],
    'pricing' => [
      0 => [
        'id' => '1',
        'name' => 'Black',
        'description' => 'Perfect for startups and growing brands.',
        'price' => '4,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social media strategy\\n2 social media platforms\\n12 premium posts/month\\n4 high-quality Reels\\nCaption writing & hashtag research\\nContent scheduling\\nMonthly analytics report\\nDedicated Account Manager',
        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
        'badge_text' => NULL,
    ],
      1 => [
        'id' => '2',
        'name' => 'Signature',
        'description' => 'Designed for brands ready to scale.',
        'price' => '7,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in BLACK\\nUp to 3 platforms\\n20 premium posts/month\\n8 Reels\\nCommunity Management\\nMonthly content planning\\nOne professional content shoot/month\\nCompetitor analysis\\nMonthly strategy meeting',
        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
        'badge_text' => NULL,
    ],
      2 => [
        'id' => '3',
        'name' => '✨ Icon',
        'description' => 'For brands that want to dominate their industry.',
        'price' => '12,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in SIGNATURE\\nUp to 4 platforms\\n30 premium posts/month\\n12 cinematic Reels\\nDaily Stories\\nFull Community Management\\nProfessional photography & videography\\nInfluencer outreach\\nAdvanced analytics & KPI reporting\\nPriority support',
        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
        'badge_text' => NULL,
    ],
      3 => [
        'id' => '4',
        'name' => 'Black Line 360°',
        'description' => 'Everything your brand needs under one agency.',
        'price' => '18,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social Media Management\\nContent Creation\\nWebsite Management\\nSEO\\nGoogle Ads\\nMeta Ads\\nTikTok Ads\\nEmail Marketing\\nInfluencer Marketing\\nMonthly Strategy Sessions\\nPerformance Reports\\nDedicated Marketing Team',
        'best_for' => NULL,
        'badge_text' => NULL,
    ],
    ],
    'created_at' => '2026-08-19T12:51:06.000000Z',
    'updated_at' => '2026-08-19T12:51:06.000000Z',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    ],
  5 => [
    'id' => 'restaurant-marketing-id',
    'title' => 'Restaurant Marketing',
    'show_in_footer' => false,
    'slug' => 'restaurant-marketing',
    'hero' => [
      'small_text' => 'RESTAURANT & HOSPITALITY MARKETING',
      'heading' => 'Fill Tables, Build Loyalty, and Make Your Venue the Talk of the City.',
      'btn_text' => 'Grow Your Foot Traffic&nbsp; →',
      'btn_link' => '/book-now',
      'image' => 'images/service/1786819879_service-page-banner.jpg',
    ],
    'overview' => [
      'label' => 'OVERVIEW',
      'description' => 'The culinary industry is fast-paced and fiercely competitive. We create mouthwatering visual storytelling, geo-targeted foot-traffic ad campaigns, food influencer tasting nights, and Google Maps optimization that consistently pack your dining room.

From high-end food photography and signature dish showcase Reels to reservation booking funnels and review generation, we turn diners into devoted regulars.',
      'sub_heading' => 'Our Restaurant Marketing Suite:',
      'bullets' => 'Appetizing Culinary Photography & Videography
Local Geo-Fenced Meta & Google Ads
Foodie & Food-Critic Influencer Tastings
Google My Business & TripAdvisor SEO',
      'image' => 'images/work-osteria.jpg',
    ],
    'benefits_header' => [
      'heading' => 'How Specialized<br>F&B Marketing Fills<br>Every Seat',
      'description' => 'Drive steady reservations on weekdays, create weekend waitlists, and establish a signature culinary brand.',
    ],
    'benefits' => [
      0 => [
        'id' => '1',
        'icon' => 'assets/icons/benefit-brand.png',
        'title' => 'Irresistible Food Imagery',
        'description' => 'Visuals that highlight culinary textures, steam, and craftsmanship to immediately stimulate appetite.',
    ],
      1 => [
        'id' => '2',
        'icon' => 'assets/icons/benefit-growth.png',
        'title' => 'Hyper-Local Foot Traffic Ads',
        'description' => 'Pinpoint ads to tourists, foodies, and residents within a 5km radius during lunch and dinner times.',
    ],
      2 => [
        'id' => '3',
        'icon' => 'assets/icons/benefit-engagement.png',
        'title' => 'Influencer Tasting Dinners',
        'description' => 'Curated tasting nights that generate dozens of viral stories and reviews in a single evening.',
    ],
      3 => [
        'id' => '4',
        'icon' => 'assets/icons/benefit-authority.png',
        'title' => 'Google Maps Dominance',
        'description' => 'Rank #1 for top local culinary searches ("best restaurant near me", "top cafes in Dubai").',
    ],
      4 => [
        'id' => '5',
        'icon' => 'assets/icons/benefit-audience.png',
        'title' => 'Repeat Diner Loyalty',
        'description' => 'Automated VIP private dining clubs, SMS notifications, and seasonal menu promotions.',
    ],
      5 => [
        'id' => '6',
        'icon' => 'assets/icons/benefit-time.png',
        'title' => 'Reputation Management',
        'description' => 'Proactive review collection on OpenTable, Google, and TripAdvisor to elevate your rating.',
    ],
    ],
    'process_header' => [
      'subheading' => 'PROCESS',
      'heading' => 'From<br>Kitchen to Fully<br>Booked<br>Tables.',
    ],
    'process' => [
      0 => [
        'id' => '1',
        'title' => 'Culinary Menu Shoot',
        'description' => 'We photograph signature dishes, cocktail artistry, interior ambiance, and chef action in high resolution.',
        'icon' => 'images/service/1786821688_search.svg',
    ],
      1 => [
        'id' => '2',
        'title' => 'Local Map Optimization',
        'description' => 'We optimize your Google Business profile, menu links, food photos, and direct reservation buttons.',
        'icon' => 'images/service/1786821709_Strategize.svg',
    ],
      2 => [
        'id' => '3',
        'title' => 'Geo-Fenced Ads',
        'description' => 'We deploy geo-fenced Instagram and TikTok ads timed precisely before meal rushes to drive reservations.',
        'icon' => 'images/service/1786821721_create.svg',
    ],
      3 => [
        'id' => '4',
        'title' => 'Foodie Influencer Tastings',
        'description' => 'We host curated tasting nights with leading regional food bloggers, critics, and lifestyle creators.',
        'icon' => 'images/service/1786821738_publish.svg',
    ],
      4 => [
        'id' => '5',
        'title' => 'Reservation & Loyalty Scaling',
        'description' => 'We analyze table bookings, review feedback, and build recurring diner retention campaigns.',
        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
    ],
    ],
    'pricing_header' => [
      'heading' => 'From Presence to Market Dominance.',
      'highlight' => 'Market Dominance.',
      'description' => 'Choose the level of strategy, creativity, and support your brand needs to grow, scale, and lead.',
    ],
    'pricing' => [
      0 => [
        'id' => '1',
        'name' => 'Black',
        'description' => 'Perfect for startups and growing brands.',
        'price' => '4,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social media strategy\\n2 social media platforms\\n12 premium posts/month\\n4 high-quality Reels\\nCaption writing & hashtag research\\nContent scheduling\\nMonthly analytics report\\nDedicated Account Manager',
        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
        'badge_text' => NULL,
    ],
      1 => [
        'id' => '2',
        'name' => 'Signature',
        'description' => 'Designed for brands ready to scale.',
        'price' => '7,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in BLACK\\nUp to 3 platforms\\n20 premium posts/month\\n8 Reels\\nCommunity Management\\nMonthly content planning\\nOne professional content shoot/month\\nCompetitor analysis\\nMonthly strategy meeting',
        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
        'badge_text' => NULL,
    ],
      2 => [
        'id' => '3',
        'name' => '✨ Icon',
        'description' => 'For brands that want to dominate their industry.',
        'price' => '12,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in SIGNATURE\\nUp to 4 platforms\\n30 premium posts/month\\n12 cinematic Reels\\nDaily Stories\\nFull Community Management\\nProfessional photography & videography\\nInfluencer outreach\\nAdvanced analytics & KPI reporting\\nPriority support',
        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
        'badge_text' => NULL,
    ],
      3 => [
        'id' => '4',
        'name' => 'Black Line 360°',
        'description' => 'Everything your brand needs under one agency.',
        'price' => '18,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social Media Management\\nContent Creation\\nWebsite Management\\nSEO\\nGoogle Ads\\nMeta Ads\\nTikTok Ads\\nEmail Marketing\\nInfluencer Marketing\\nMonthly Strategy Sessions\\nPerformance Reports\\nDedicated Marketing Team',
        'best_for' => NULL,
        'badge_text' => NULL,
    ],
    ],
    'created_at' => '2026-08-19T12:51:06.000000Z',
    'updated_at' => '2026-08-19T12:51:06.000000Z',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    ],
  6 => [
    'id' => 'social-media-management-id',
    'title' => 'Social Media Management',
    'show_in_footer' => false,
    'slug' => 'social-media-management',
    'hero' => [
      'small_text' => 'SOCIAL MEDIA MANAGEMENT',
      'heading' => 'Your Brand Deserves More Than a Feed.',
      'btn_text' => 'Book a Discovery Call&nbsp; →',
      'btn_link' => '/book-now',
      'image' => 'images/service/1786819879_service-page-banner.jpg',
    ],
    'overview' => [
      'label' => 'OVERVIEW',
      'description' => 'At Black Line Marketing, we turn social media into a powerful extension of your brand. We build strategic, visually compelling social experiences designed to capture attention, build meaningful connections, and drive growth.

From content planning and creative production to publishing and community management, we handle every part of your social presence with purpose — ensuring your brand stays consistent, relevant, and impossible to ignore.',
      'sub_heading' => 'Our Social Media Expertise:',
      'bullets' => 'Strategic Content Planning
Creative Content & Storytelling
Community Engagement & Management
Performance Tracking & Optimization',
      'image' => 'images/service/1786820363_3e21a292ef2acb2f4638dacec719d43784164505.jpg',
    ],
    'benefits_header' => [
      'heading' => 'What Strategic Social<br>Media Can Do for Your<br>Brand',
      'description' => 'More than content. More than followers. A strategic social presence built to create attention, influence, and measurable growth.',
    ],
    'benefits' => [
      0 => [
        'id' => '1',
        'icon' => 'assets/icons/benefit-brand.png',
        'title' => 'Build Brand Recognition',
        'description' => 'Create a consistent and recognizable presence across every social platform, making your brand easier to remember.',
    ],
      1 => [
        'id' => '2',
        'icon' => 'assets/icons/benefit-engagement.png',
        'title' => 'Increase Engagement',
        'description' => 'Create content that makes people stop scrolling, interact, share, and build a stronger connection with your brand.',
    ],
      2 => [
        'id' => '3',
        'icon' => 'assets/icons/benefit-audience.png',
        'title' => 'Grow Your Audience',
        'description' => 'Reach the right people through platform-specific strategies, relevant content, and consistent audience growth.',
    ],
      3 => [
        'id' => '4',
        'icon' => 'assets/icons/benefit-authority.png',
        'title' => 'Strengthen Brand Authority',
        'description' => 'Position your brand as credible, relevant, and worth following through strategic and valuable content.',
    ],
      4 => [
        'id' => '5',
        'icon' => 'assets/icons/benefit-time.png',
        'title' => 'Save Time',
        'description' => 'We handle planning, creation, scheduling, publishing, and management so you can focus on running your business.',
    ],
      5 => [
        'id' => '6',
        'icon' => 'assets/icons/benefit-growth.png',
        'title' => 'Drive Business Growth',
        'description' => 'Turn social media attention into meaningful opportunities, helping generate awareness, leads, and long-term growth.',
    ],
    ],
    'process_header' => [
      'subheading' => 'PROCESS',
      'heading' => 'From<br>Strategy to<br>Social<br>Growth.',
    ],
    'process' => [
      0 => [
        'id' => '1',
        'title' => 'Discover',
        'description' => 'We understand your brand, audience, competitors, and goals.',
        'icon' => 'images/service/1786821688_search.svg',
    ],
      1 => [
        'id' => '2',
        'title' => 'Strategize',
        'description' => 'We create your social media strategy, content pillars, and monthly plan.',
        'icon' => 'images/service/1786821709_Strategize.svg',
    ],
      2 => [
        'id' => '3',
        'title' => 'Create',
        'description' => 'We develop high-quality posts, Reels, Stories, captions, and campaigns.',
        'icon' => 'images/service/1786821721_create.svg',
    ],
      3 => [
        'id' => '4',
        'title' => 'Publish & Manage',
        'description' => 'We schedule content, manage your channels, and engage with your audience.',
        'icon' => 'images/service/1786821738_publish.svg',
    ],
      4 => [
        'id' => '5',
        'title' => 'Analyze & Optimize',
        'description' => 'We track performance and continuously refine the strategy.',
        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
    ],
    ],
    'pricing_header' => [
      'heading' => 'From Presence to Market Dominance.',
      'highlight' => 'Market Dominance.',
      'description' => 'Choose the level of strategy, creativity, and support your brand needs to grow, scale, and lead.',
    ],
    'pricing' => [
      0 => [
        'id' => '1',
        'name' => 'Black',
        'description' => 'Perfect for startups and growing brands.',
        'price' => '4,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social media strategy\\n2 social media platforms\\n12 premium posts/month\\n4 high-quality Reels\\nCaption writing & hashtag research\\nContent scheduling\\nMonthly analytics report\\nDedicated Account Manager',
        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
        'badge_text' => NULL,
    ],
      1 => [
        'id' => '2',
        'name' => 'Signature',
        'description' => 'Designed for brands ready to scale.',
        'price' => '7,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in BLACK\\nUp to 3 platforms\\n20 premium posts/month\\n8 Reels\\nCommunity Management\\nMonthly content planning\\nOne professional content shoot/month\\nCompetitor analysis\\nMonthly strategy meeting',
        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
        'badge_text' => NULL,
    ],
      2 => [
        'id' => '3',
        'name' => '✨ Icon',
        'description' => 'For brands that want to dominate their industry.',
        'price' => '12,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in SIGNATURE\\nUp to 4 platforms\\n30 premium posts/month\\n12 cinematic Reels\\nDaily Stories\\nFull Community Management\\nProfessional photography & videography\\nInfluencer outreach\\nAdvanced analytics & KPI reporting\\nPriority support',
        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
        'badge_text' => NULL,
    ],
      3 => [
        'id' => '4',
        'name' => 'Black Line 360°',
        'description' => 'Everything your brand needs under one agency.',
        'price' => '18,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social Media Management\\nContent Creation\\nWebsite Management\\nSEO\\nGoogle Ads\\nMeta Ads\\nTikTok Ads\\nEmail Marketing\\nInfluencer Marketing\\nMonthly Strategy Sessions\\nPerformance Reports\\nDedicated Marketing Team',
        'best_for' => NULL,
        'badge_text' => NULL,
    ],
    ],
    'created_at' => '2026-08-19T12:51:06.000000Z',
    'updated_at' => '2026-08-19T12:51:06.000000Z',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    ],
  7 => [
    'id' => 'website-development-id',
    'title' => 'Website Development',
    'show_in_footer' => false,
    'slug' => 'website-development',
    'hero' => [
      'small_text' => 'CUSTOM WEBSITE DEVELOPMENT',
      'heading' => 'Digital Experiences Built for Speed, Scale & Sales.',
      'btn_text' => 'Start Your Project&nbsp; →',
      'btn_link' => '/book-now',
      'image' => 'images/service/1786819879_service-page-banner.jpg',
    ],
    'overview' => [
      'label' => 'OVERVIEW',
      'description' => 'Your website is your 24/7 salesperson. We build custom-coded, high-performance web platforms that not only look visually stunning but are engineered from the ground up for seamless user experiences and exceptional conversion rates.

From high-converting landing pages to complex e-commerce architectures, our development team ensures flawless functionality, blazing-fast load times, and robust SEO foundations.',
      'sub_heading' => 'Our Development Expertise:',
      'bullets' => 'Custom Web Applications & CMS
High-Performance E-Commerce Solutions
Responsive UI/UX Design
Technical SEO & Performance Optimization',
      'image' => 'images/work-meridian.jpg',
    ],
    'benefits_header' => [
      'heading' => 'Why Custom Web<br>Development Wins',
      'description' => 'A template cannot reflect a premium brand. Own a digital asset that outpaces competitors and turns visitors into revenue.',
    ],
    'benefits' => [
      0 => [
        'id' => '1',
        'icon' => 'assets/icons/benefit-brand.png',
        'title' => 'Bespoke UI/UX Design',
        'description' => 'Unique interfaces tailored specifically to your brand identity, free from the constraints of rigid templates.',
    ],
      1 => [
        'id' => '2',
        'icon' => 'assets/icons/benefit-engagement.png',
        'title' => 'Blazing Fast Performance',
        'description' => 'Optimized codebases and modern tech stacks that ensure sub-second load times for maximum retention.',
    ],
      2 => [
        'id' => '3',
        'icon' => 'assets/icons/benefit-audience.png',
        'title' => 'Conversion-Optimized',
        'description' => 'Strategic user journeys and frictionless checkout flows designed strictly to increase your bottom line.',
    ],
      3 => [
        'id' => '4',
        'icon' => 'assets/icons/benefit-growth.png',
        'title' => 'Mobile-First Architecture',
        'description' => 'Flawless rendering and intuitive interaction across smartphones, tablets, and desktop displays.',
    ],
      4 => [
        'id' => '5',
        'icon' => 'assets/icons/benefit-authority.png',
        'title' => 'Advanced Security',
        'description' => 'Enterprise-grade security protocols to protect your business data and build trust with your customers.',
    ],
      5 => [
        'id' => '6',
        'icon' => 'assets/icons/benefit-time.png',
        'title' => 'Scalable Infrastructure',
        'description' => 'Built on robust frameworks that easily scale to handle massive traffic spikes as your business grows.',
    ],
    ],
    'process_header' => [
      'subheading' => 'PROCESS',
      'heading' => 'From Architecture to<br>Global Launch.',
    ],
    'process' => [
      0 => [
        'id' => '1',
        'title' => 'Discovery & Wireframing',
        'description' => 'We map out the user journey, site architecture, and functional requirements.',
        'icon' => 'images/service/1786821688_search.svg',
    ],
      1 => [
        'id' => '2',
        'title' => 'UI/UX Design',
        'description' => 'We create high-fidelity, interactive prototypes of your new digital experience.',
        'icon' => 'images/service/1786821709_Strategize.svg',
    ],
      2 => [
        'id' => '3',
        'title' => 'Full-Stack Development',
        'description' => 'Our engineers write clean, scalable code to bring the design to life on front and back ends.',
        'icon' => 'images/service/1786821721_create.svg',
    ],
      3 => [
        'id' => '4',
        'title' => 'QA & Stress Testing',
        'description' => 'Rigorous testing across browsers, devices, and varying network speeds to ensure stability.',
        'icon' => 'images/service/1786821738_publish.svg',
    ],
      4 => [
        'id' => '5',
        'title' => 'Deployment & Handoff',
        'description' => 'We handle domain configuration, server deployment, and train your team on the CMS.',
        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
    ],
    ],
    'pricing_header' => [
      'heading' => 'From Presence to Market Dominance.',
      'highlight' => 'Market Dominance.',
      'description' => 'Choose the level of strategy, creativity, and support your brand needs to grow, scale, and lead.',
    ],
    'pricing' => [
      0 => [
        'id' => '1',
        'name' => 'Black',
        'description' => 'Perfect for startups and growing brands.',
        'price' => '4,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social media strategy\\n2 social media platforms\\n12 premium posts/month\\n4 high-quality Reels\\nCaption writing & hashtag research\\nContent scheduling\\nMonthly analytics report\\nDedicated Account Manager',
        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
        'badge_text' => NULL,
    ],
      1 => [
        'id' => '2',
        'name' => 'Signature',
        'description' => 'Designed for brands ready to scale.',
        'price' => '7,500',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in BLACK\\nUp to 3 platforms\\n20 premium posts/month\\n8 Reels\\nCommunity Management\\nMonthly content planning\\nOne professional content shoot/month\\nCompetitor analysis\\nMonthly strategy meeting',
        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
        'badge_text' => NULL,
    ],
      2 => [
        'id' => '3',
        'name' => '✨ Icon',
        'description' => 'For brands that want to dominate their industry.',
        'price' => '12,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Everything in SIGNATURE\\nUp to 4 platforms\\n30 premium posts/month\\n12 cinematic Reels\\nDaily Stories\\nFull Community Management\\nProfessional photography & videography\\nInfluencer outreach\\nAdvanced analytics & KPI reporting\\nPriority support',
        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
        'badge_text' => NULL,
    ],
      3 => [
        'id' => '4',
        'name' => 'Black Line 360°',
        'description' => 'Everything your brand needs under one agency.',
        'price' => '18,000',
        'price_small' => '/month',
        'btn_text' => 'Speak to Us',
        'btn_link' => '/book-now',
        'bullets' => 'Social Media Management\\nContent Creation\\nWebsite Management\\nSEO\\nGoogle Ads\\nMeta Ads\\nTikTok Ads\\nEmail Marketing\\nInfluencer Marketing\\nMonthly Strategy Sessions\\nPerformance Reports\\nDedicated Marketing Team',
        'best_for' => NULL,
        'badge_text' => NULL,
    ],
    ],
    'created_at' => '2026-08-19T12:51:06.000000Z',
    'updated_at' => '2026-08-19T12:51:06.000000Z',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    ],
];

        foreach ($services as $s) {
            Service::create($s);
        }
    }
}
