<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Service;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $services = [
            // 1. Social Media Management
            [
                'id' => 'social-media-management-id',
                'title' => 'Social Media Management',
                'slug' => 'social-media-management',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'SOCIAL MEDIA MANAGEMENT',
                    'heading' => 'Your Brand Deserves More Than a Feed.',
                    'btn_text' => 'Book a Discovery Call&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "At Black Line Marketing, we turn social media into a powerful extension of your brand. We build strategic, visually compelling social experiences designed to capture attention, build meaningful connections, and drive growth.\n\nFrom content planning and creative production to publishing and community management, we handle every part of your social presence with purpose — ensuring your brand stays consistent, relevant, and impossible to ignore.",
                    'sub_heading' => 'Our Social Media Expertise:',
                    'bullets' => "Strategic Content Planning\nCreative Content & Storytelling\nCommunity Engagement & Management\nPerformance Tracking & Optimization",
                    'image' => 'images/service/1786820363_3e21a292ef2acb2f4638dacec719d43784164505.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'What Strategic Social<br>Media Can Do for Your<br>Brand',
                    'description' => 'More than content. More than followers. A strategic social presence built to create attention, influence, and measurable growth.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'Build Brand Recognition',
                        'description' => 'Create a consistent and recognizable presence across every social platform, making your brand easier to remember.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Increase Engagement',
                        'description' => 'Create content that makes people stop scrolling, interact, share, and build a stronger connection with your brand.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Grow Your Audience',
                        'description' => 'Reach the right people through platform-specific strategies, relevant content, and consistent audience growth.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Strengthen Brand Authority',
                        'description' => 'Position your brand as credible, relevant, and worth following through strategic and valuable content.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Save Time',
                        'description' => 'We handle planning, creation, scheduling, publishing, and management so you can focus on running your business.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Drive Business Growth',
                        'description' => 'Turn social media attention into meaningful opportunities, helping generate awareness, leads, and long-term growth.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'From<br>Strategy to<br>Social<br>Growth.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Discover',
                        'description' => 'We understand your brand, audience, competitors, and goals.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Strategize',
                        'description' => 'We create your social media strategy, content pillars, and monthly plan.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Create',
                        'description' => 'We develop high-quality posts, Reels, Stories, captions, and campaigns.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Publish & Manage',
                        'description' => 'We schedule content, manage your channels, and engage with your audience.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Analyze & Optimize',
                        'description' => 'We track performance and continuously refine the strategy.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'From Presence to Market Dominance.',
                    'highlight' => 'Market Dominance.',
                    'description' => 'Choose the level of strategy, creativity, and support your brand needs to grow, scale, and lead.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Black',
                        'description' => 'Perfect for startups and growing brands.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social media strategy\n2 social media platforms\n12 premium posts/month\n4 high-quality Reels\nCaption writing & hashtag research\nContent scheduling\nMonthly analytics report\nDedicated Account Manager',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Signature',
                        'description' => 'Designed for brands ready to scale.',
                        'price' => '7,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in BLACK\nUp to 3 platforms\n20 premium posts/month\n8 Reels\nCommunity Management\nMonthly content planning\nOne professional content shoot/month\nCompetitor analysis\nMonthly strategy meeting',
                        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Icon',
                        'description' => 'For brands that want to dominate their industry.',
                        'price' => '12,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in SIGNATURE\nUp to 4 platforms\n30 premium posts/month\n12 cinematic Reels\nDaily Stories\nFull Community Management\nProfessional photography & videography\nInfluencer outreach\nAdvanced analytics & KPI reporting\nPriority support',
                        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Everything your brand needs under one agency.',
                        'price' => '18,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social Media Management\nContent Creation\nWebsite Management\nSEO\nGoogle Ads\nMeta Ads\nTikTok Ads\nEmail Marketing\nInfluencer Marketing\nMonthly Strategy Sessions\nPerformance Reports\nDedicated Marketing Team',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],

            // 2. Paid Advertising
            [
                'id' => 'paid-advertising-id',
                'title' => 'Paid Advertising',
                'slug' => 'paid-advertising',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'PAID ADVERTISING & PERFORMANCE MARKETING',
                    'heading' => 'Turn Ad Spend into Predictable, Profitable Revenue.',
                    'btn_text' => 'Scale Your Revenue&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "Stop burning budget on unoptimized ads. We engineer high-performing ad campaigns across Meta, Google, TikTok, and LinkedIn designed for maximum ROI and predictable scaling.\n\nFrom conversion-focused ad creatives and precise audience targeting to continuous A/B testing and funnel optimization, we transform digital advertising into your most reliable customer acquisition engine.",
                    'sub_heading' => 'Our Advertising Capabilities:',
                    'bullets' => "Meta Ads (Instagram & Facebook)\nGoogle Search, Display & Performance Max\nTikTok & LinkedIn Paid Campaigns\nConversion Rate & Retargeting Funnels",
                    'image' => 'images/work-meridian.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'Why Performance<br>Advertising Drives<br>Measurable Scale',
                    'description' => 'Eliminate guesswork with scientific performance marketing, lower customer acquisition costs, and higher return on ad spend (ROAS).',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Predictable ROAS',
                        'description' => 'Scalable advertising frameworks designed to reliably deliver 3x-8x return on your advertising budget.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Precision Targeting',
                        'description' => 'Reach high-intent buyers based on real demographic, behavioral, and interest intelligence.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'High-Converting Creatives',
                        'description' => 'Dynamic video hooks, static graphics, and persuasive copywriting built to convert scrollers into buyers.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Full-Funnel Retargeting',
                        'description' => 'Re-engage warm prospects who visited your site or engaged with your brand until they convert.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Transparent Attribution',
                        'description' => 'Clear attribution models, live KPI dashboards, and deep metric insights with zero vanity metrics.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Rapid Budget Scaling',
                        'description' => 'Seamlessly increase ad spend while maintaining profitable cost-per-acquisition (CPA) and margin.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'From<br>Data Audit to<br>Exponential<br>Return.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Audit & Tracking',
                        'description' => 'We audit existing ad accounts, install server-side pixel tracking, and verify conversion APIs.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Funnel Architecture',
                        'description' => 'We design full-funnel ad architectures tailored to cold, warm, and hot buyer segments.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Creative Production',
                        'description' => 'We produce thumb-stopping ad creatives, direct-response hooks, and persuasive copy.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Testing & Launch',
                        'description' => 'We deploy multivariate testing across audiences, placements, offers, and creative variations.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Scale & Optimize',
                        'description' => 'We allocate budget aggressively to winning ads and continuously lower acquisition costs.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Transparent Ad Management for High Growth.',
                    'highlight' => 'High Growth.',
                    'description' => 'Select the performance management tier that aligns with your ad spend and revenue goals.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Black',
                        'description' => 'Perfect for startups and growing brands.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social media strategy\n2 social media platforms\n12 premium posts/month\n4 high-quality Reels\nCaption writing & hashtag research\nContent scheduling\nMonthly analytics report\nDedicated Account Manager',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Signature',
                        'description' => 'Designed for brands ready to scale.',
                        'price' => '7,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in BLACK\nUp to 3 platforms\n20 premium posts/month\n8 Reels\nCommunity Management\nMonthly content planning\nOne professional content shoot/month\nCompetitor analysis\nMonthly strategy meeting',
                        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Icon',
                        'description' => 'For brands that want to dominate their industry.',
                        'price' => '12,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in SIGNATURE\nUp to 4 platforms\n30 premium posts/month\n12 cinematic Reels\nDaily Stories\nFull Community Management\nProfessional photography & videography\nInfluencer outreach\nAdvanced analytics & KPI reporting\nPriority support',
                        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Everything your brand needs under one agency.',
                        'price' => '18,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social Media Management\nContent Creation\nWebsite Management\nSEO\nGoogle Ads\nMeta Ads\nTikTok Ads\nEmail Marketing\nInfluencer Marketing\nMonthly Strategy Sessions\nPerformance Reports\nDedicated Marketing Team',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],

            // 3. Instagram Growth
            [
                'id' => 'instagram-growth-id',
                'title' => 'Instagram Growth',
                'slug' => 'instagram-growth',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'INSTAGRAM GROWTH & AUTHORITY',
                    'heading' => 'Cultivate a Cult Following That Converts Into Loyal Buyers.',
                    'btn_text' => 'Grow Your Instagram&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "Instagram is your brand's digital flagship store and most influential customer touchpoint. We craft curated visual identities, viral Reel formats, and interactive Story funnels that turn passive scrollers into passionate brand advocates.\n\nBy leveraging algorithm-aligned organic strategies combined with active community nurturing, we establish your brand as an undisputed authority in your niche.",
                    'sub_heading' => 'Our Instagram Growth Pillars:',
                    'bullets' => "High-Retention Reels & Visual Aesthetics\nStory Sequences & DM Funnel Conversions\nHashtag, SEO & Audio Trend Integration\nCommunity Engagement & Growth Hacking",
                    'image' => 'images/work-nova.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'The Power of<br>Organic Instagram<br>Authority',
                    'description' => 'Unlock genuine engagement, consistent viral reach, and a committed community that values and trusts your brand.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'Aesthetic Excellence',
                        'description' => 'A cohesive, luxury visual grid that leaves an unforgettable first impression on profile visitors.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Viral Reel Velocity',
                        'description' => 'Engineered video concepts that capitalize on trending audio and high watch-time algorithms.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Targeted Followers',
                        'description' => 'Attract real, niche-relevant followers who actively care about your products and services.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'DM Sales Funnels',
                        'description' => 'Convert Story viewers and commenters into sales conversations and qualified business leads.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Enhanced Social Proof',
                        'description' => 'Verified authority and industry recognition that elevates your perceived brand value.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Hands-Off Management',
                        'description' => 'Complete end-to-end management so your feed stays active, engaging, and growing daily.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'The Instagram<br>Acceleration<br>Blueprint.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Profile Optimization',
                        'description' => 'We revamp your bio, highlights, grid aesthetic, and link-in-bio funnel architecture.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Content Matrix',
                        'description' => 'We formulate weekly Reels concepts, carousels, and high-retention Story sequences.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Visual Creation',
                        'description' => 'We produce crisp, color-graded photos and cinematic short-form vertical videos.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Algorithmic Distribution',
                        'description' => 'We publish at peak engagement windows with strategic SEO keywords and audio tracks.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Audience Nurturing',
                        'description' => 'We engage top industry accounts, manage comments, and nurture DM relationships.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Tailored Packages for Instagram Scale.',
                    'highlight' => 'Instagram Scale.',
                    'description' => 'Choose the right velocity of content and management to accelerate your profile.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Black',
                        'description' => 'Perfect for startups and growing brands.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social media strategy\n2 social media platforms\n12 premium posts/month\n4 high-quality Reels\nCaption writing & hashtag research\nContent scheduling\nMonthly analytics report\nDedicated Account Manager',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Signature',
                        'description' => 'Designed for brands ready to scale.',
                        'price' => '7,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in BLACK\nUp to 3 platforms\n20 premium posts/month\n8 Reels\nCommunity Management\nMonthly content planning\nOne professional content shoot/month\nCompetitor analysis\nMonthly strategy meeting',
                        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Icon',
                        'description' => 'For brands that want to dominate their industry.',
                        'price' => '12,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in SIGNATURE\nUp to 4 platforms\n30 premium posts/month\n12 cinematic Reels\nDaily Stories\nFull Community Management\nProfessional photography & videography\nInfluencer outreach\nAdvanced analytics & KPI reporting\nPriority support',
                        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Everything your brand needs under one agency.',
                        'price' => '18,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social Media Management\nContent Creation\nWebsite Management\nSEO\nGoogle Ads\nMeta Ads\nTikTok Ads\nEmail Marketing\nInfluencer Marketing\nMonthly Strategy Sessions\nPerformance Reports\nDedicated Marketing Team',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],

            // 4. TikTok Strategy
            [
                'id' => 'tiktok-strategy-id',
                'title' => 'TikTok Strategy',
                'slug' => 'tiktok-strategy',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'TIKTOK STRATEGY & CREATIVE PRODUCTION',
                    'heading' => 'Capture Modern Attention with Native TikTok Storytelling.',
                    'btn_text' => 'Dominate TikTok Now&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "Traditional advertising does not work on TikTok. Brands must speak the native visual language of trends, fast hooks, and cultural moments. We create high-impact, short-form video strategies that feel organic yet strategically guide viewers toward your offerings.\n\nFrom trend forecasting and hook scripting to creator-style shooting and TikTok Spark Ads, we turn TikTok into an unstoppable awareness and revenue channel.",
                    'sub_heading' => 'Our TikTok Capabilities:',
                    'bullets' => "Native TikTok Creative & Trend Forecasting\nFast-Paced Scripting & Hook Optimization\nTikTok Shop & Conversion Integrations\nTikTok Spark Ads & Creator Collaborations",
                    'image' => 'images/work-aurelio.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'Unlock Massive<br>Organic & Paid Reach<br>on TikTok',
                    'description' => 'Reach millions of potential customers with authentic, entertaining, and conversion-focused video content.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Algorithmic Velocity',
                        'description' => 'Rapid organic distribution to hyper-targeted audiences on the "For You" Page (FYP).',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => '3-Second Hook Science',
                        'description' => 'Proven hook formulas designed to immediately stop the scroll and maximize watch time.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Next-Gen Buyer Appeal',
                        'description' => 'Authentic brand positioning that resonates deeply with Gen Z and millennial consumers.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Trend Capitalization',
                        'description' => 'Rapid turnaround on viral sounds, audio trends, and culturally relevant formats.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'TikTok Shop Integration',
                        'description' => 'Seamless in-app product tagging and frictionless checkout user experiences.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Spark Ad Amplification',
                        'description' => 'Boost top-performing organic videos with targeted paid ad spend for exponential scale.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'From<br>Trend Concept to<br>FYP Virality.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Trend Audit',
                        'description' => 'We analyze winning competitor angles, viral formats, and audio trends in your niche.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Hook & Scripting',
                        'description' => 'We write engaging, authentic scripts with proven 3-second visual and audio hooks.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Native Production',
                        'description' => 'We shoot and edit fast-cut vertical videos with dynamic captions and sound effects.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Channel Publishing',
                        'description' => 'We post natively with trending audio, optimized descriptions, and search keywords.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Spark Ad Scaling',
                        'description' => 'We analyze retention curves and turn top-performing organic videos into high-ROI Spark Ads.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Strategic Tiers for TikTok Domination.',
                    'highlight' => 'TikTok Domination.',
                    'description' => 'Packages designed to flood your feed with high-converting short-form videos.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Black',
                        'description' => 'Perfect for startups and growing brands.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social media strategy\n2 social media platforms\n12 premium posts/month\n4 high-quality Reels\nCaption writing & hashtag research\nContent scheduling\nMonthly analytics report\nDedicated Account Manager',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Signature',
                        'description' => 'Designed for brands ready to scale.',
                        'price' => '7,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in BLACK\nUp to 3 platforms\n20 premium posts/month\n8 Reels\nCommunity Management\nMonthly content planning\nOne professional content shoot/month\nCompetitor analysis\nMonthly strategy meeting',
                        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Icon',
                        'description' => 'For brands that want to dominate their industry.',
                        'price' => '12,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in SIGNATURE\nUp to 4 platforms\n30 premium posts/month\n12 cinematic Reels\nDaily Stories\nFull Community Management\nProfessional photography & videography\nInfluencer outreach\nAdvanced analytics & KPI reporting\nPriority support',
                        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Everything your brand needs under one agency.',
                        'price' => '18,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social Media Management\nContent Creation\nWebsite Management\nSEO\nGoogle Ads\nMeta Ads\nTikTok Ads\nEmail Marketing\nInfluencer Marketing\nMonthly Strategy Sessions\nPerformance Reports\nDedicated Marketing Team',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],

            // 5. Brand Identity
            [
                'id' => 'brand-identity-id',
                'title' => 'Brand Identity',
                'slug' => 'brand-identity',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'BRAND IDENTITY & DESIGN SYSTEMS',
                    'heading' => 'Build an Iconic Brand That Commands Uncompromising Respect.',
                    'btn_text' => 'Craft Your Identity&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "A logo is not a brand. A brand is the distinct emotional feeling, visual prestige, and unforgettable reputation you cultivate in the minds of your market. We engineer comprehensive identity systems that elevate your market positioning and justify premium pricing.\n\nFrom logo design and bespoke typography to color psychology, brand guidelines, and packaging design, we build timeless brands designed to lead categories.",
                    'sub_heading' => 'Our Branding Expertise:',
                    'bullets' => "Core Brand Strategy & Market Positioning\nLogo Marks, Typography & Color Systems\nBrand Voice, Tone & Messaging Guidelines\nCollateral, Packaging & Digital Asset Design",
                    'image' => 'images/the-world-most-iconic.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'What a World-Class<br>Brand Identity<br>Delivers',
                    'description' => 'Position your business as the obvious choice, command premium rates, and stand out in crowded markets.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'Instant Recognition',
                        'description' => 'Distinct visual assets that ensure your company is immediately recognized and remembered.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Premium Pricing Power',
                        'description' => 'Elevate perceived brand value so you can charge top-tier market prices with confidence.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Total Brand Consistency',
                        'description' => 'Comprehensive brand guidelines that ensure flawless execution across digital and physical mediums.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Emotional Resonance',
                        'description' => 'Build deep consumer loyalty and trust that outlasts fleeting market trends.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Scalable Asset Library',
                        'description' => 'Complete vector libraries and brand toolkits ready for digital, print, and physical signage.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Market Differentiation',
                        'description' => 'Carve out a defensible and unique aesthetic space separate from all direct competitors.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'The Identity<br>Creation<br>Journey.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Brand Immersion',
                        'description' => 'We explore your vision, values, competitors, target audience, and positioning goals.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Strategic Architecture',
                        'description' => 'We define your brand archetype, voice, tone, positioning statement, and core narrative.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Visual Exploration',
                        'description' => 'We develop 3 distinct creative visual identity concepts with moodboards and logo directions.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'System Refinement',
                        'description' => 'We polish the chosen direction into complete logo systems, typography, color palettes, and mockups.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Brand Bible Delivery',
                        'description' => 'We deliver a comprehensive Brand Guideline Bible and all production-ready master vector assets.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Bespoke Identity Packages.',
                    'highlight' => 'Identity Packages.',
                    'description' => 'Investments that define the lasting legacy and market stature of your business.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Black',
                        'description' => 'Perfect for startups and growing brands.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social media strategy\n2 social media platforms\n12 premium posts/month\n4 high-quality Reels\nCaption writing & hashtag research\nContent scheduling\nMonthly analytics report\nDedicated Account Manager',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Signature',
                        'description' => 'Designed for brands ready to scale.',
                        'price' => '7,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in BLACK\nUp to 3 platforms\n20 premium posts/month\n8 Reels\nCommunity Management\nMonthly content planning\nOne professional content shoot/month\nCompetitor analysis\nMonthly strategy meeting',
                        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Icon',
                        'description' => 'For brands that want to dominate their industry.',
                        'price' => '12,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in SIGNATURE\nUp to 4 platforms\n30 premium posts/month\n12 cinematic Reels\nDaily Stories\nFull Community Management\nProfessional photography & videography\nInfluencer outreach\nAdvanced analytics & KPI reporting\nPriority support',
                        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Everything your brand needs under one agency.',
                        'price' => '18,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social Media Management\nContent Creation\nWebsite Management\nSEO\nGoogle Ads\nMeta Ads\nTikTok Ads\nEmail Marketing\nInfluencer Marketing\nMonthly Strategy Sessions\nPerformance Reports\nDedicated Marketing Team',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],

            // 6. Creative Direction
            [
                'id' => 'creative-direction-id',
                'title' => 'Creative Direction',
                'slug' => 'creative-direction',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'CREATIVE DIRECTION & PRODUCTION',
                    'heading' => 'Mastermind Your Visual World with Haute Creative Direction.',
                    'btn_text' => 'Direct Your Next Campaign&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "Exceptional visual storytelling requires vision, precision, and relentless curation. We lead creative campaigns, photoshoots, commercial video productions, and art direction that transform standard marketing into arresting visual art.\n\nFrom high-fashion editorial concepts and product launches to luxury campaign storytelling, our creative directors orchestrate every detail from moodboard to final cut.",
                    'sub_heading' => 'Our Creative Leadership:',
                    'bullets' => "Campaign Concepting & Storyboarding\nEditorial & Commercial Photoshoot Direction\nCinematic Commercial & Video Production\nSet Styling, Casting & Art Direction",
                    'image' => 'images/ce777daf76ee5541c189407447390a60a69f9148.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'The Value of<br>Elite Creative<br>Direction',
                    'description' => 'Elevate your brand beyond commerce into a coveted cultural symbol through world-class visual execution.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'Haute Visual Aesthetics',
                        'description' => 'Editorial-grade production value that rivals global luxury fashion houses.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Cohesive Storytelling',
                        'description' => 'Every frame, color tone, and typography choice tells a singular, powerful brand narrative.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Turnkey Production',
                        'description' => 'We coordinate model casting, locations, lighting, wardrobe styling, and post-production.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Cinematic Video Assets',
                        'description' => '4K/6K commercial films that captivate audiences across web, social, and broadcast.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Multi-Format Versatility',
                        'description' => 'Assets shot and framed specifically for billboard, web hero, and vertical mobile formats.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Unmatched Cultural Impact',
                        'description' => 'Turn product launches into unforgettable industry moments that spark viral conversation.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'The Haute<br>Production<br>Methodology.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Creative Brief',
                        'description' => 'We develop the mood, aesthetic vision, color palettes, and core narrative pillars.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Pre-Production',
                        'description' => 'We script scenes, design shot lists, cast talent, and secure premium filming locations.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'On-Set Art Direction',
                        'description' => 'Our creative directors oversee lighting, styling, camera movements, and talent performance.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Post-Production',
                        'description' => 'We perform cinema-grade color grading, sound design, visual effects, and master editing.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Multi-Format Delivery',
                        'description' => 'We output all campaign assets in customized aspect ratios optimized for every marketing channel.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'World-Class Creative Packages.',
                    'highlight' => 'Creative Packages.',
                    'description' => 'Retainers and project-based direction tailored to ambitious brands and luxury labels.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Black',
                        'description' => 'Perfect for startups and growing brands.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social media strategy\n2 social media platforms\n12 premium posts/month\n4 high-quality Reels\nCaption writing & hashtag research\nContent scheduling\nMonthly analytics report\nDedicated Account Manager',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Signature',
                        'description' => 'Designed for brands ready to scale.',
                        'price' => '7,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in BLACK\nUp to 3 platforms\n20 premium posts/month\n8 Reels\nCommunity Management\nMonthly content planning\nOne professional content shoot/month\nCompetitor analysis\nMonthly strategy meeting',
                        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Icon',
                        'description' => 'For brands that want to dominate their industry.',
                        'price' => '12,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in SIGNATURE\nUp to 4 platforms\n30 premium posts/month\n12 cinematic Reels\nDaily Stories\nFull Community Management\nProfessional photography & videography\nInfluencer outreach\nAdvanced analytics & KPI reporting\nPriority support',
                        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Everything your brand needs under one agency.',
                        'price' => '18,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social Media Management\nContent Creation\nWebsite Management\nSEO\nGoogle Ads\nMeta Ads\nTikTok Ads\nEmail Marketing\nInfluencer Marketing\nMonthly Strategy Sessions\nPerformance Reports\nDedicated Marketing Team',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],

            // 7. Influencer Marketing
            [
                'id' => 'influencer-marketing-id',
                'title' => 'Influencer Marketing',
                'slug' => 'influencer-marketing',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'INFLUENCER MARKETING & TALENT PARTNERSHIPS',
                    'heading' => 'Harness the Power of Authentic, High-Converting Creator Endorsement.',
                    'btn_text' => 'Launch Creator Campaigns&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "Consumer trust is built through authentic third-party validation. We connect your brand with carefully curated creators, tastemakers, and niche authority figures whose audiences align seamlessly with your ideal customer profile.\n\nFrom talent identification and contract negotiations to creative briefs, gifting campaigns, and ROI tracking, we manage seamless influencer activations that drive genuine engagement and sales.",
                    'sub_heading' => 'Our Influencer Management:',
                    'bullets' => "Creator Discovery & Audience Vetting\nContract Negotiations & Usage Rights\nCreative Briefing & Campaign Coordination\nAffiliate Tracking, Whitelisting & ROI Analysis",
                    'image' => 'images/work-osteria.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'Why Influencer<br>Endorsement Outperforms<br>Standard Ads',
                    'description' => 'Leverage established trust, cultural credibility, and authentic community connections to scale brand growth.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'High-Trust Endorsements',
                        'description' => 'Audiences purchase faster when products are recommended by creators they know and trust.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Zero Fake Followers',
                        'description' => 'Rigorous vetting to ensure real engagement rates, clean demographic data, and active followers.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'High-Volume UGC Library',
                        'description' => 'Accumulate a library of user-generated content for use across paid ads and organic channels.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Creator Whitelisting',
                        'description' => 'Run paid ads directly through creators\' personal accounts for lower CPA and higher click-through.',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Turnkey Management',
                        'description' => 'We handle all logistics, product gifting deliveries, contracts, compliance, and payments.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Trackable Revenue & ROI',
                        'description' => 'Transparent tracking via customized promo codes, affiliate links, and pixel conversion data.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'From<br>Talent Sourcing to<br>Scalable<br>Conversions.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Creator Alignment',
                        'description' => 'We identify and vet creators whose audience demographics match your exact buyer persona.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Negotiation & Legal',
                        'description' => 'We handle talent outreach, contract terms, digital usage rights, deliverables, and timelines.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Creative Briefing',
                        'description' => 'We supply creative briefs that empower authentic expression while safeguarding brand messaging.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Campaign Rollout',
                        'description' => 'We manage product delivery, review pre-publish drafts, and coordinate synchronized posting dates.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Whitelisting & ROI',
                        'description' => 'We amplify top creator posts with paid ads and provide comprehensive revenue analytics.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Scalable Influencer Programs.',
                    'highlight' => 'Influencer Programs.',
                    'description' => 'Targeted campaigns designed to build credibility and drive measurable consumer demand.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Black',
                        'description' => 'Perfect for startups and growing brands.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social media strategy\n2 social media platforms\n12 premium posts/month\n4 high-quality Reels\nCaption writing & hashtag research\nContent scheduling\nMonthly analytics report\nDedicated Account Manager',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Signature',
                        'description' => 'Designed for brands ready to scale.',
                        'price' => '7,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in BLACK\nUp to 3 platforms\n20 premium posts/month\n8 Reels\nCommunity Management\nMonthly content planning\nOne professional content shoot/month\nCompetitor analysis\nMonthly strategy meeting',
                        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Icon',
                        'description' => 'For brands that want to dominate their industry.',
                        'price' => '12,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in SIGNATURE\nUp to 4 platforms\n30 premium posts/month\n12 cinematic Reels\nDaily Stories\nFull Community Management\nProfessional photography & videography\nInfluencer outreach\nAdvanced analytics & KPI reporting\nPriority support',
                        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Everything your brand needs under one agency.',
                        'price' => '18,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social Media Management\nContent Creation\nWebsite Management\nSEO\nGoogle Ads\nMeta Ads\nTikTok Ads\nEmail Marketing\nInfluencer Marketing\nMonthly Strategy Sessions\nPerformance Reports\nDedicated Marketing Team',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],

            // 8. Restaurant Marketing
            [
                'id' => 'restaurant-marketing-id',
                'title' => 'Restaurant Marketing',
                'slug' => 'restaurant-marketing',
                'show_in_footer' => true,
                'hero' => [
                    'small_text' => 'RESTAURANT & HOSPITALITY MARKETING',
                    'heading' => 'Fill Tables, Build Loyalty, and Make Your Venue the Talk of the City.',
                    'btn_text' => 'Grow Your Foot Traffic&nbsp; →',
                    'btn_link' => route('book-now', [], false) ?: '/book-now',
                    'image' => 'images/service/1786819879_service-page-banner.jpg',
                ],
                'overview' => [
                    'label' => 'OVERVIEW',
                    'description' => "The culinary industry is fast-paced and fiercely competitive. We create mouthwatering visual storytelling, geo-targeted foot-traffic ad campaigns, food influencer tasting nights, and Google Maps optimization that consistently pack your dining room.\n\nFrom high-end food photography and signature dish showcase Reels to reservation booking funnels and review generation, we turn diners into devoted regulars.",
                    'sub_heading' => 'Our Restaurant Marketing Suite:',
                    'bullets' => "Appetizing Culinary Photography & Videography\nLocal Geo-Fenced Meta & Google Ads\nFoodie & Food-Critic Influencer Tastings\nGoogle My Business & TripAdvisor SEO",
                    'image' => 'images/work-osteria.jpg',
                ],
                'benefits_header' => [
                    'heading' => 'How Specialized<br>F&B Marketing Fills<br>Every Seat',
                    'description' => 'Drive steady reservations on weekdays, create weekend waitlists, and establish a signature culinary brand.',
                ],
                'benefits' => [
                    [
                        'id' => '1',
                        'icon' => 'assets/icons/benefit-brand.png',
                        'title' => 'Irresistible Food Imagery',
                        'description' => 'Visuals that highlight culinary textures, steam, and craftsmanship to immediately stimulate appetite.',
                    ],
                    [
                        'id' => '2',
                        'icon' => 'assets/icons/benefit-growth.png',
                        'title' => 'Hyper-Local Foot Traffic Ads',
                        'description' => 'Pinpoint ads to tourists, foodies, and residents within a 5km radius during lunch and dinner times.',
                    ],
                    [
                        'id' => '3',
                        'icon' => 'assets/icons/benefit-engagement.png',
                        'title' => 'Influencer Tasting Dinners',
                        'description' => 'Curated tasting nights that generate dozens of viral stories and reviews in a single evening.',
                    ],
                    [
                        'id' => '4',
                        'icon' => 'assets/icons/benefit-authority.png',
                        'title' => 'Google Maps Dominance',
                        'description' => 'Rank #1 for top local culinary searches ("best restaurant near me", "top cafes in Dubai").',
                    ],
                    [
                        'id' => '5',
                        'icon' => 'assets/icons/benefit-audience.png',
                        'title' => 'Repeat Diner Loyalty',
                        'description' => 'Automated VIP private dining clubs, SMS notifications, and seasonal menu promotions.',
                    ],
                    [
                        'id' => '6',
                        'icon' => 'assets/icons/benefit-time.png',
                        'title' => 'Reputation Management',
                        'description' => 'Proactive review collection on OpenTable, Google, and TripAdvisor to elevate your rating.',
                    ],
                ],
                'process_header' => [
                    'subheading' => 'PROCESS',
                    'heading' => 'From<br>Kitchen to Fully<br>Booked<br>Tables.',
                ],
                'process' => [
                    [
                        'id' => '1',
                        'title' => 'Culinary Menu Shoot',
                        'description' => 'We photograph signature dishes, cocktail artistry, interior ambiance, and chef action in high resolution.',
                        'icon' => 'images/service/1786821688_search.svg',
                    ],
                    [
                        'id' => '2',
                        'title' => 'Local Map Optimization',
                        'description' => 'We optimize your Google Business profile, menu links, food photos, and direct reservation buttons.',
                        'icon' => 'images/service/1786821709_Strategize.svg',
                    ],
                    [
                        'id' => '3',
                        'title' => 'Geo-Fenced Ads',
                        'description' => 'We deploy geo-fenced Instagram and TikTok ads timed precisely before meal rushes to drive reservations.',
                        'icon' => 'images/service/1786821721_create.svg',
                    ],
                    [
                        'id' => '4',
                        'title' => 'Foodie Influencer Tastings',
                        'description' => 'We host curated tasting nights with leading regional food bloggers, critics, and lifestyle creators.',
                        'icon' => 'images/service/1786821738_publish.svg',
                    ],
                    [
                        'id' => '5',
                        'title' => 'Reservation & Loyalty Scaling',
                        'description' => 'We analyze table bookings, review feedback, and build recurring diner retention campaigns.',
                        'icon' => 'images/service/1786821753_Analyze & Optimize.svg',
                    ],
                ],
                'pricing_header' => [
                    'heading' => 'Tailored Packages for Hospitality & Dining.',
                    'highlight' => 'Hospitality & Dining.',
                    'description' => 'Proven growth strategies designed specifically for cafes, fine dining, lounges, and restaurant groups.',
                ],
                'pricing' => [
                    [
                        'id' => '1',
                        'name' => 'Black',
                        'description' => 'Perfect for startups and growing brands.',
                        'price' => '4,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social media strategy\n2 social media platforms\n12 premium posts/month\n4 high-quality Reels\nCaption writing & hashtag research\nContent scheduling\nMonthly analytics report\nDedicated Account Manager',
                        'best_for' => '&bull; Restaurants &nbsp;&nbsp;&nbsp; &bull; Beauty<br>&bull; Startups',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '2',
                        'name' => 'Signature',
                        'description' => 'Designed for brands ready to scale.',
                        'price' => '7,500',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in BLACK\nUp to 3 platforms\n20 premium posts/month\n8 Reels\nCommunity Management\nMonthly content planning\nOne professional content shoot/month\nCompetitor analysis\nMonthly strategy meeting',
                        'best_for' => '&bull; Fashion &nbsp;&nbsp;&nbsp; &bull; Hospitality<br>&bull; Clinics &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; Real Estate Agencies',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '3',
                        'name' => '✨ Icon',
                        'description' => 'For brands that want to dominate their industry.',
                        'price' => '12,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Everything in SIGNATURE\nUp to 4 platforms\n30 premium posts/month\n12 cinematic Reels\nDaily Stories\nFull Community Management\nProfessional photography & videography\nInfluencer outreach\nAdvanced analytics & KPI reporting\nPriority support',
                        'best_for' => '&bull; Luxury Brands &nbsp; &bull; Hotels<br>&bull; Personal Brands &bull; Premium Restaurants<br>&bull; Developers',
                        'badge_text' => null,
                    ],
                    [
                        'id' => '4',
                        'name' => 'Black Line 360°',
                        'description' => 'Everything your brand needs under one agency.',
                        'price' => '18,000',
                        'price_small' => '/month',
                        'btn_text' => 'Speak to Us',
                        'btn_link' => '/book-now',
                        'bullets' => 'Social Media Management\nContent Creation\nWebsite Management\nSEO\nGoogle Ads\nMeta Ads\nTikTok Ads\nEmail Marketing\nInfluencer Marketing\nMonthly Strategy Sessions\nPerformance Reports\nDedicated Marketing Team',
                        'best_for' => null,
                        'badge_text' => null,
                    ],
                ],
            ],
        ];

        foreach ($services as $serviceData) {
            Service::updateOrCreate(
                ['slug' => $serviceData['slug']],
                $serviceData
            );
        }
    }
}
